/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.57
 * Generated at: 2026-09-05 13:08:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.eauction.model.Item;
import com.eauction.model.User;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.eauction.model.Item");
    _jspx_imports_classes.add("com.eauction.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    User loggedInUser = (User) session.getAttribute("currentUser");

    if (loggedInUser == null) {
        response.sendRedirect("signin.html");
        return;
    }

    List<Item> itemList = (List<Item>) request.getAttribute("itemList");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Dashboard - E-Auction Platform</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f4f6f9;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        header {\r\n");
      out.write("            background-color: #101827;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            height: 84px;\r\n");
      out.write("            padding: 0 7%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            border-top: 3px solid #f59e0b;\r\n");
      out.write("            box-shadow: 0 3px 12px rgba(0,0,0,0.25);\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            letter-spacing: -1px;\r\n");
      out.write("        }\r\n");
      out.write("        .logo span { color: #f59e0b; }\r\n");
      out.write("\r\n");
      out.write("        .user-menu { position: relative; }\r\n");
      out.write("\r\n");
      out.write("        .user-trigger {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 9px;\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            border: 1px solid #f59e0b;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            padding: 8px 14px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .user-trigger:hover { background: rgba(245,158,11,0.1); }\r\n");
      out.write("\r\n");
      out.write("        .avatar {\r\n");
      out.write("            width: 28px;\r\n");
      out.write("            height: 28px;\r\n");
      out.write("            background: #f59e0b;\r\n");
      out.write("            color: #111827;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            flex-shrink: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .chevron { font-size: 10px; transition: transform 0.2s; }\r\n");
      out.write("        .user-menu.open .chevron { transform: rotate(180deg); }\r\n");
      out.write("\r\n");
      out.write("        .dropdown {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            top: calc(100% + 8px);\r\n");
      out.write("            background: #1e293b;\r\n");
      out.write("            border: 1px solid #334155;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            min-width: 180px;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0,0,0,0.4);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            z-index: 2000;\r\n");
      out.write("        }\r\n");
      out.write("        .user-menu.open .dropdown { display: block; }\r\n");
      out.write("\r\n");
      out.write("        .dropdown-header {\r\n");
      out.write("            padding: 12px 16px;\r\n");
      out.write("            border-bottom: 1px solid #334155;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-header .name { font-weight: bold; font-size: 14px; color: white; }\r\n");
      out.write("        .dropdown-header .email { font-size: 12px; color: #9ca3af; margin-top: 3px; word-break: break-all; }\r\n");
      out.write("\r\n");
      out.write("        .dropdown a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 11px 16px;\r\n");
      out.write("            color: #f87171;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-top: 1px solid #334155;\r\n");
      out.write("            transition: background 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown a:hover { background: rgba(248,113,113,0.1); }\r\n");
      out.write("        main {\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("        .welcome-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 1px 3px rgba(0,0,0,0.1);\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-add-item {\r\n");
      out.write("            background-color: #f59e0b;\r\n");
      out.write("            color: #111827;\r\n");
      out.write("            padding: 10px 18px;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .items-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 1px 3px rgba(0,0,0,0.1);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Added image banner styling */\r\n");
      out.write("        .item-image {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 180px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            border-bottom: 1px solid #e2e8f0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item-body {\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item-price {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #059669;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <a class=\"logo\" href=\"DashboardServlet\">E-<span>Auction</span></a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"addItem.jsp\" class=\"btn-add-item\">+ Add New Item</a>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"user-menu\" id=\"userMenu\">\r\n");
      out.write("            <button class=\"user-trigger\" onclick=\"toggleDropdown()\">\r\n");
      out.write("                <div class=\"avatar\">");
      out.print( loggedInUser.getName().trim().substring(0,1).toUpperCase() );
      out.write("</div>\r\n");
      out.write("                Welcome, ");
      out.print( loggedInUser.getName() );
      out.write("\r\n");
      out.write("                <span class=\"chevron\">&#9660;</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"dropdown\">\r\n");
      out.write("                <div class=\"dropdown-header\">\r\n");
      out.write("                    <div class=\"name\">");
      out.print( loggedInUser.getName() );
      out.write("</div>\r\n");
      out.write("                    <div class=\"email\">");
      out.print( loggedInUser.getEmail() );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"LogoutServlet\">&#x2192; Logout</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("        <section class=\"welcome-card\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h2>Live Auctions</h2>\r\n");
      out.write("                <p style=\"margin-top: 0.5rem; color: #64748b;\">Active items fetched directly from Oracle DB.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"items-grid\">\r\n");
      out.write("        ");

            if (itemList != null && !itemList.isEmpty()) {
                for (Item item : itemList) {
        
      out.write("\r\n");
      out.write("            <div class=\"item-card\">\r\n");
      out.write("                <!-- Render image tag fetched from item_picture column -->\r\n");
      out.write("                <img class=\"item-image\" \r\n");
      out.write("                     src=\"");
      out.print( (item.getItemPicture() != null && !item.getItemPicture().trim().isEmpty()) ? item.getItemPicture() : "images/placeholder.png" );
      out.write("\" \r\n");
      out.write("                     alt=\"");
      out.print( item.getItemName() );
      out.write("\"\r\n");
      out.write("                     onerror=\"this.onerror=null; this.src='https://via.placeholder.com/280x180?text=No+Image';\" />\r\n");
      out.write("\r\n");
      out.write("                <div class=\"item-body\">\r\n");
      out.write("                    <h3>");
      out.print( item.getItemName() );
      out.write("</h3>\r\n");
      out.write("                    <p style=\"color: #64748b;\">");
      out.print( item.getItemDescription() );
      out.write("</p>\r\n");
      out.write("                    <div class=\"item-price\">₹");
      out.print( item.getStartingPrice() );
      out.write("</div>\r\n");
      out.write("                    <small style=\"color: #94a3b8;\">Seller: ");
      out.print( item.getSellerEmail() );
      out.write("</small>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");

                }
            } else {
        
      out.write("\r\n");
      out.write("            <p style=\"color: #64748b;\">No active auctions listed yet.</p>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function toggleDropdown() {\r\n");
      out.write("            document.getElementById(\"userMenu\").classList.toggle(\"open\");\r\n");
      out.write("        }\r\n");
      out.write("        document.addEventListener(\"click\", function (e) {\r\n");
      out.write("            const menu = document.getElementById(\"userMenu\");\r\n");
      out.write("            if (!menu.contains(e.target)) menu.classList.remove(\"open\");\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
